### PR TITLE
feat: add mkdocs-jupyter plugin

### PR DESCRIPTION
**Pull request by nadworny**
This introduces support for the mkdocs-jupyter plugin.

### CODE REVIEW

**Comment by nadworny** [comment]
Hi there,

I would appreciate some help :) as suggested, I have included my local version of mkdocs-techdocs-core in a Dockerfile which I use for my backstage deployment, but I'm getting the following error while opening my techdocs:
```
space-backstage-backstage-1  | 2022-05-17T19:14:00.228Z techdocs error Failed to build the docs page: Failed to generate docs from /space into /tmp/techdocs-tmp-HDHqU0; caused by unknown error 'Command mkdocs failed, exit code: 1' Failed to generate docs from /space into /tmp/techdocs-tmp-HDHqU0; caused by unknown error 'Command mkdocs failed, exit code: 1' type=plugin name=Error cause=undefined stack=Error: Failed to generate docs from /space into /tmp/techdocs-tmp-HDHqU0; caused by unknown error 'Command mkdocs failed, exit code: 1'
space-backstage-backstage-1  |     at _TechdocsGenerator.run (/app/node_modules/@backstage/plugin-techdocs-node/dist/index.cjs.js:412:13)
space-backstage-backstage-1  |     at runMicrotasks (<anonymous>)
space-backstage-backstage-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
space-backstage-backstage-1  |     at async DocsBuilder.build (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:137:5)
space-backstage-backstage-1  |     at async DocsSynchronizer.doSync (/app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:222:23)
space-backstage-backstage-1  |     at async /app/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:520:7
```

Do you see anything important missing in the implementation? Or do you have any idea what I might be doing wrong?

**Comment by realabja** [comment]
Is there any update on this?

**Comment by nadworny** [comment]
hi @ottosichert / @freben (sorry for mentioning but you're the only ones I know from the backstage project from my previous PRs) - do you know if this repo is still active? Any help would be appreciated...

**Comment by nadworny** [comment]
I guess this repo is dead? 😢

**Comment by agentbellnorm** [comment]
@nadworny to answer your (old) question: Did you list the plugin under the `plugins` key in `mkdocs.yaml`?

Generally we don't want to add more plugins to this core repo as not everyone will use it. I have a PR to add some instructions on how to use mkdocs plugins here: https://github.com/backstage/backstage/pull/19607

**Pull request closed without merging**
