### PR TITLE
Set minimum supported Python version to 3.9

### PR DESCRIPTION
**Pull request by deejay1**
Remove unsupported Python interpreters and update renovate action

### CODE REVIEW

**Review by awanlin — APPROVED** [review]
Looks good, let's merge this in 👍

**Comment by deejay1** [comment]
Build will pass as soon as I rebase this against https://github.com/backstage/mkdocs-techdocs-core/pull/227

**Comment by awanlin** [comment]
Ready for you to rebase when you have time @deejay1 👍

**Comment by deejay1** [comment]
@awanlin done

**Pull request merged**
