### PR TITLE
chore(deps): update mkdocs-material to v8.5.9

### PR DESCRIPTION
**Pull request by ruarfff**
This change also required updating pygments to v2.12 and pymdown-extensions to v9.8.

A lot of new features have been added to mkdocs-material since 8.1.

In [8.2](https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.0) we got:

- native support for Mermaid.js diagrams
- native support for tags (with search integration)

We use tags a lot in our company, and it was a pain point migrating our mkdocs into backstage. We have a workaround, installing the newer version of mkcdocs-material in the backstage Dockerfile. Still, it is harder to have a good local setup for repos that want to use the techdocs plugin with mkdocs-material.

In [8.3](https://github.com/squidfunk/mkdocs-material/releases/tag/8.3.0) we got:

- support for custom admonition icons
- support for linking of content tabs
- support for boosting pages in search
- support for hiding footer navigation
- previous/next indicators to content tabs
- Improved typeset link colors in light and dark mode

In [8.4](https://github.com/squidfunk/mkdocs-material/releases/tag/8.4.0) we got:

- support for cookie consent
- support for feedback widget (Was this page helpful?)
- support for dismissable announcement bar

In [8.5](https://github.com/squidfunk/mkdocs-material/releases/tag/8.5.0) we got:

- support for social cards
- support for code annotation anchor links (deep linking)
- support for code annotation comment stripping (syntax modifier)
- support for sidebars scrolling automatically to active item
- support for anchor following table of contents (= auto scroll)
- support for tag icons

If this update could be added, it would make our lives much easier. We have tested this on our instance of backstage and have not identified any breaking changes. 

Thank you!

### CODE REVIEW

**Comment by StephaneRob** [comment]
I also tested to update mkdocs material, mainly to use mermaid instead of kroki. To make it work, I had to remove `pymdownx.extra` from `markdown_extensions` (conflict?)

https://github.com/StephaneRob/mkdocs-techdocs-core/commit/480258c3c237aea0562dd369c808d9abd2107583

**Comment by askreet** [comment]
There's interest in native support for Mermaid at my company, hope to see this land soon.

**Comment by ruarfff** [comment]
> I also tested to update mkdocs material, mainly to use mermaid instead of kroki. To make it work, I had to remove `pymdownx.extra` from `markdown_extensions` (conflict?)
> 
> [StephaneRob@480258c](https://github.com/StephaneRob/mkdocs-techdocs-core/commit/480258c3c237aea0562dd369c808d9abd2107583)

I am not sure @StephaneRob. I did not encounter any issues that required that change. What was the issue you saw? Do you have some way to reproduce it? 

I have been using this library version, and it worked on my sites without needing further modifications. If you have a setup I should test with please let me know.

**Comment by StephaneRob** [comment]
@ruarfff looks like the JS to initialize mermaid graph is not executed in Backstage context.
I had to create a custom addon (`TechDocsAddonLocations.Content`) to initialize them. I have to retry with `pymdownx.extra` to see if i can initialize mermaid correctly.

**Comment by agentbellnorm** [comment]
@ruarfff, I'll close this PR since #109 was merged!

**Comment by ruarfff** [comment]
Thank you @agentbellnorm :)

**Pull request closed without merging**
