### PR TITLE
chore(renovate): refactor config file

### PR DESCRIPTION
**Pull request by MindTooth**
I noticed the config was old and could need a update:

```
$ renovate-config-validator renovate.json5

 INFO: Validating renovate.json5
 WARN: Config migration necessary
       "oldConfig": {
         "labels": ["dependencies"],
         "extends": ["config:base", ":disableDependencyDashboard", ":gitSignOff"],
         "ignoreDeps": ["mkdocs-material"],
         "packageRules": [{"matchLanguages": ["python"], "rangeStrategy": "widen"}]
       },
       "newConfig": {
         "labels": ["dependencies"],
         "extends": [
           "config:recommended",
           ":disableDependencyDashboard",
           ":gitSignOff"
         ],
         "ignoreDeps": ["mkdocs-material"],
         "packageRules": [{"matchCategories": ["python"], "rangeStrategy": "widen"}]
       }
 INFO: Config validated successfully
```

---

- Changed to using plain `.json` ending
- Added schema notation on top
- Converted to extend
- Renamed `config:base` to `config:recommended`

**Question?** One question, now that we are on the latest `mkdocs-material`, should we then remove the ignore and rather split on major/minor so that updates will still be added?  Or we can limit updates within the same x.y.

---

With the changes:

```
$ renovate-config-validator .github/renovate.json

 INFO: Validating .github/renovate.json
 INFO: Config validated successfully
 ```

### CODE REVIEW

**Comment by MindTooth** [comment]
@johnphilip283 thoughts?

**Comment by johnphilip283** [comment]
Hey there @MindTooth! Thank you for the PR. We'd like to be on the safer side with `mkdocs-material` upgrades, so I believe limiting updates within the same x.y would be a nice way to do this. Otherwise, the rest of the changes LGTM!

**Comment by MindTooth** [comment]
I've updated the config to use [`allowedVersions`](https://docs.renovatebot.com/configuration-options/#allowedversions) to limit the range.

**Comment by MindTooth** [comment]
@johnphilip283 need anything more from me? :smile:

**Comment by MindTooth** [comment]
Feel like I'm in a whack-a-mole game with the Stale bot. 🤣 

whack-a-mole gif

**Review by alexlorenzi — APPROVED** [review]
Hey @MindTooth  - Thanks for the contribution. Appreciate your input

**Pull request merged**
