### PR TITLE
Add Renovate config file

### PR DESCRIPTION
**Pull request by jairhenrique**
Add Renovate config file!

### CODE REVIEW

**Review by camilaibs — COMMENTED** [review]
Hi @jairhenrique, so nice to see you contributing again, thank you!
We have been using [renovate](https://docs.renovatebot.com/) instead of `dependabot` for the Backstage repositories, here is an [example](https://github.com/backstage/backstage/pull/12888) of a pull request. Do you have any concerns about using `renovate`?

**Comment by jairhenrique** [comment]
@camilaibs I have never used renovate. I like dependabot because it also updates github-actions, I use it in my personal and company projects.

Apparently the configuration of renovate is done by the administrators and not by configuration files.

Do you think I should close this pull request?

**Comment by camilaibs** [comment]
> @camilaibs I have never used renovate. I like dependabot because it also updates github-actions, I use it in my personal and company projects.
> 
> Apparently the configuration of renovate is done by the administrators and not by configuration files.
> 
> Do you think I should close this pull request?

It looks like we can use a [configuration file](https://docs.renovatebot.com/configuration-options/) as we have it [here](https://github.com/backstage/backstage/blob/master/.github/renovate.json5), we can ask for support from my colleagues at @backstage/maintainers if you are still happy to help us with this configuration using renovate, we will definitely appreciate your help.

**Comment by benjdlambert** [comment]
Hey @jairhenrique :wave:

Friendly neighbourhood maintainer here :wave:

I think if you want to copy in the config, and we can enable renovate here too. Don't think that should be an issue. Would be nice to keep the organisation on one method to be honest without having different sources for updating. :pray:

**Comment by jairhenrique** [comment]
@camilaibs @benjdlambert I replaced dependabot with renovate file, based on [backstage project](https://github.com/backstage/backstage/blob/master/.github/renovate.json5)!

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
I updated the bot to be enabled on this repo - just need an approval from @camilaibs and merge and it should just magically work ✨

**Review by camilaibs — APPROVED** [review]

**Pull request merged**
