### PR TITLE
Run tests on python 3.10

### PR DESCRIPTION
**Pull request by jairhenrique**
Include python 3.10 to test matrix.

### CODE REVIEW

**Comment by camilaibs** [comment]
Hi 👋🏻 , could you add a pull request description?

**Comment by jairhenrique** [comment]
> Hi 👋🏻 , could you add a pull request description?

Hi @camilaibs.
There is a PR template? I don't saw the `CONTRIBUTING.md` file on `.github` folder.

**Comment by camilaibs** [comment]
> > Hi 👋🏻 , could you add a pull request description?
> 
> Hi @camilaibs. There is a PR template? I don't saw the `CONTRIBUTING.md` file on `.github` folder.

Not for this repository, but we have a small release section in the readme:
https://github.com/backstage/mkdocs-techdocs-core#release

Do you have any suggestions for models (one you like)? We'd also love another contribution by doing this if you want to help us again!

**Comment by jairhenrique** [comment]
@camilaibs I put this change in `Unrelease` section.

**Pull request merged**
